events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl;
        
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        
        auth_basic "Security Playground";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        location / {
            proxy_pass http://security-playground:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}